# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node 12.13 LTS
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 12.13
      - name: Install NPM dependencies
        run: npm install
      - name: Lint with ESLint
        run: npm run lint
      - name: Build
        run: npm build
      
    # - name: deploy
    #   run: 
    #       git config --global user.name $user_name
    #       git config --global user.email $user_email
    #       git remote set-url origin https://${github_token}@github.com/${repository}
    #       npm run deploy
    #   env:
    #       user_name: 'github-actions[bot]'
    #       user_email: 'github-actions[bot]@users.noreply.github.com'
    #       github_token: ${{ secrets.ACTIONS_DEPLOYMENT_TOKEN }}
    #       repository: ${{ github.repository }}
        
